// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

type WorkflowAgentSnapshot struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
	Contents  []byte `json:"contents"`
}

type WorkflowRun struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
	Version  int64  `json:"version"`
}
