// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sql

import (
	"context"
)

const createAgentSnapshot = `-- name: CreateAgentSnapshot :exec
INSERT INTO workflow_agent_snapshots (run_name, agent_name, contents)
VALUES ($1, $2, $3)
`

type CreateAgentSnapshotParams struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
	Contents  []byte `json:"contents"`
}

func (q *Queries) CreateAgentSnapshot(ctx context.Context, arg CreateAgentSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSnapshot, arg.RunName, arg.AgentName, arg.Contents)
	return err
}

const createRun = `-- name: CreateRun :one
INSERT INTO workflow_runs (name, contents)
VALUES ($1, $2)
RETURNING name, contents, version
`

type CreateRunParams struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.Name, arg.Contents)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}

const deleteRun = `-- name: DeleteRun :execrows
DELETE FROM workflow_runs
WHERE name = $1
`

func (q *Queries) DeleteRun(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRun, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentSnapshot = `-- name: GetAgentSnapshot :one
SELECT contents
FROM workflow_agent_snapshots
WHERE run_name = $1 AND agent_name = $2
`

type GetAgentSnapshotParams struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
}

func (q *Queries) GetAgentSnapshot(ctx context.Context, arg GetAgentSnapshotParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getAgentSnapshot, arg.RunName, arg.AgentName)
	var contents []byte
	err := row.Scan(&contents)
	return contents, err
}

const getRun = `-- name: GetRun :one
SELECT name, contents, version
FROM workflow_runs
WHERE name = $1
`

func (q *Queries) GetRun(ctx context.Context, name string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, name)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT name, contents, version
FROM workflow_runs
ORDER BY name
`

func (q *Queries) ListRuns(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(&i.Name, &i.Contents, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :one
UPDATE workflow_runs
SET contents = $2, version = version + 1
WHERE name = $1 AND version = $3
RETURNING name, contents, version
`

type UpdateRunParams struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
	Version  int64  `json:"version"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, updateRun, arg.Name, arg.Contents, arg.Version)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}
