// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"context"
)

type Querier interface {
	CreateAgentSnapshot(ctx context.Context, arg CreateAgentSnapshotParams) error
	CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error)
	DeleteRun(ctx context.Context, name string) (int64, error)
	GetAgentSnapshot(ctx context.Context, arg GetAgentSnapshotParams) ([]byte, error)
	GetRun(ctx context.Context, name string) (WorkflowRun, error)
	ListRuns(ctx context.Context) ([]WorkflowRun, error)
	UpdateRun(ctx context.Context, arg UpdateRunParams) (WorkflowRun, error)
}

var _ Querier = (*Queries)(nil)
