// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type Publication struct {
	SessionName string `json:"session_name"`
	Contents    []byte `json:"contents"`
	Version     int64  `json:"version"`
}

type Session struct {
	Name            string       `json:"name"`
	IntentID        string       `json:"intent_id"`
	RuntimeScope    string       `json:"runtime_scope"`
	Image           string       `json:"image"`
	Definition      []byte       `json:"definition"`
	Repository      string       `json:"repository"`
	InitialRef      string       `json:"initial_ref"`
	WorkflowRun     string       `json:"workflow_run"`
	WorkflowStep    string       `json:"workflow_step"`
	DeletionStorage sql.NullBool `json:"deletion_storage"`
	CreatedAt       int64        `json:"created_at"`
}

type SessionTask struct {
	SessionName        string        `json:"session_name"`
	TaskID             string        `json:"task_id"`
	Prompt             string        `json:"prompt"`
	TimeoutNanoseconds int64         `json:"timeout_nanoseconds"`
	ResultKind         string        `json:"result_kind"`
	State              string        `json:"state"`
	Outcome            []byte        `json:"outcome"`
	PullRequest        []byte        `json:"pull_request"`
	WorkflowOutput     []byte        `json:"workflow_output"`
	Failure            string        `json:"failure"`
	CreatedAt          int64         `json:"created_at"`
	FinishedAt         sql.NullInt64 `json:"finished_at"`
	ChangeInput        []byte        `json:"change_input"`
	ChangeArtifact     []byte        `json:"change_artifact"`
}

type WorkflowAgentSnapshot struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
	Contents  []byte `json:"contents"`
}

type WorkflowRun struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
	Version  int64  `json:"version"`
}
