// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"context"
)

type Querier interface {
	ClearSessionDeletion(ctx context.Context, name string) (int64, error)
	CountActiveSessionTasks(ctx context.Context, sessionName string) (int64, error)
	CreateAgentSnapshot(ctx context.Context, arg CreateAgentSnapshotParams) error
	CreatePublication(ctx context.Context, arg CreatePublicationParams) (Publication, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error)
	CreateSessionTask(ctx context.Context, arg CreateSessionTaskParams) error
	DeleteRun(ctx context.Context, name string) (int64, error)
	DeleteSession(ctx context.Context, name string) (int64, error)
	GetAgentSnapshot(ctx context.Context, arg GetAgentSnapshotParams) ([]byte, error)
	GetLatestSessionTask(ctx context.Context, sessionName string) (SessionTask, error)
	GetPublication(ctx context.Context, sessionName string) (Publication, error)
	GetRun(ctx context.Context, name string) (WorkflowRun, error)
	GetSession(ctx context.Context, name string) (Session, error)
	ListDeletingSessions(ctx context.Context) ([]Session, error)
	ListRuns(ctx context.Context) ([]WorkflowRun, error)
	SetSessionDeletion(ctx context.Context, arg SetSessionDeletionParams) (int64, error)
	UpdatePublication(ctx context.Context, arg UpdatePublicationParams) (Publication, error)
	UpdateRun(ctx context.Context, arg UpdateRunParams) (WorkflowRun, error)
	UpdateSessionTask(ctx context.Context, arg UpdateSessionTaskParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
