// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sql

import (
	"context"
	"database/sql"
)

const clearSessionDeletion = `-- name: ClearSessionDeletion :execrows
UPDATE sessions
SET deletion_storage = NULL
WHERE name = $1
`

func (q *Queries) ClearSessionDeletion(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearSessionDeletion, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveSessionTasks = `-- name: CountActiveSessionTasks :one
SELECT COUNT(*)
FROM session_tasks
WHERE session_name = $1 AND state IN ('pending', 'running')
`

func (q *Queries) CountActiveSessionTasks(ctx context.Context, sessionName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSessionTasks, sessionName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentSnapshot = `-- name: CreateAgentSnapshot :exec
INSERT INTO workflow_agent_snapshots (run_name, agent_name, contents)
VALUES ($1, $2, $3)
`

type CreateAgentSnapshotParams struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
	Contents  []byte `json:"contents"`
}

func (q *Queries) CreateAgentSnapshot(ctx context.Context, arg CreateAgentSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSnapshot, arg.RunName, arg.AgentName, arg.Contents)
	return err
}

const createPublication = `-- name: CreatePublication :one
INSERT INTO publications (session_name, contents)
VALUES ($1, $2)
RETURNING session_name, contents, version
`

type CreatePublicationParams struct {
	SessionName string `json:"session_name"`
	Contents    []byte `json:"contents"`
}

func (q *Queries) CreatePublication(ctx context.Context, arg CreatePublicationParams) (Publication, error) {
	row := q.db.QueryRowContext(ctx, createPublication, arg.SessionName, arg.Contents)
	var i Publication
	err := row.Scan(&i.SessionName, &i.Contents, &i.Version)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO workflow_runs (name, contents)
VALUES ($1, $2)
RETURNING name, contents, version
`

type CreateRunParams struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.Name, arg.Contents)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}

const createSession = `-- name: CreateSession :execrows
INSERT INTO sessions (
    name, intent_id, runtime_scope, image, definition, repository, initial_ref,
    workflow_run, workflow_step, deletion_storage, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NULL, $10)
ON CONFLICT (name) DO NOTHING
`

type CreateSessionParams struct {
	Name         string `json:"name"`
	IntentID     string `json:"intent_id"`
	RuntimeScope string `json:"runtime_scope"`
	Image        string `json:"image"`
	Definition   []byte `json:"definition"`
	Repository   string `json:"repository"`
	InitialRef   string `json:"initial_ref"`
	WorkflowRun  string `json:"workflow_run"`
	WorkflowStep string `json:"workflow_step"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSession,
		arg.Name,
		arg.IntentID,
		arg.RuntimeScope,
		arg.Image,
		arg.Definition,
		arg.Repository,
		arg.InitialRef,
		arg.WorkflowRun,
		arg.WorkflowStep,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSessionTask = `-- name: CreateSessionTask :exec
INSERT INTO session_tasks (
    session_name, task_id, prompt, timeout_nanoseconds, result_kind, state,
    change_input, outcome, pull_request, workflow_output, change_artifact,
    failure, created_at, finished_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateSessionTaskParams struct {
	SessionName        string        `json:"session_name"`
	TaskID             string        `json:"task_id"`
	Prompt             string        `json:"prompt"`
	TimeoutNanoseconds int64         `json:"timeout_nanoseconds"`
	ResultKind         string        `json:"result_kind"`
	State              string        `json:"state"`
	ChangeInput        []byte        `json:"change_input"`
	Outcome            []byte        `json:"outcome"`
	PullRequest        []byte        `json:"pull_request"`
	WorkflowOutput     []byte        `json:"workflow_output"`
	ChangeArtifact     []byte        `json:"change_artifact"`
	Failure            string        `json:"failure"`
	CreatedAt          int64         `json:"created_at"`
	FinishedAt         sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) CreateSessionTask(ctx context.Context, arg CreateSessionTaskParams) error {
	_, err := q.db.ExecContext(ctx, createSessionTask,
		arg.SessionName,
		arg.TaskID,
		arg.Prompt,
		arg.TimeoutNanoseconds,
		arg.ResultKind,
		arg.State,
		arg.ChangeInput,
		arg.Outcome,
		arg.PullRequest,
		arg.WorkflowOutput,
		arg.ChangeArtifact,
		arg.Failure,
		arg.CreatedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteRun = `-- name: DeleteRun :execrows
DELETE FROM workflow_runs
WHERE name = $1
`

func (q *Queries) DeleteRun(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRun, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE name = $1
`

func (q *Queries) DeleteSession(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentSnapshot = `-- name: GetAgentSnapshot :one
SELECT contents
FROM workflow_agent_snapshots
WHERE run_name = $1 AND agent_name = $2
`

type GetAgentSnapshotParams struct {
	RunName   string `json:"run_name"`
	AgentName string `json:"agent_name"`
}

func (q *Queries) GetAgentSnapshot(ctx context.Context, arg GetAgentSnapshotParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getAgentSnapshot, arg.RunName, arg.AgentName)
	var contents []byte
	err := row.Scan(&contents)
	return contents, err
}

const getLatestSessionTask = `-- name: GetLatestSessionTask :one
SELECT session_name, task_id, prompt, timeout_nanoseconds, result_kind, state,
       outcome, pull_request, workflow_output, failure, created_at, finished_at,
       change_input, change_artifact
FROM session_tasks
WHERE session_name = $1
ORDER BY created_at DESC, task_id DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionTask(ctx context.Context, sessionName string) (SessionTask, error) {
	row := q.db.QueryRowContext(ctx, getLatestSessionTask, sessionName)
	var i SessionTask
	err := row.Scan(
		&i.SessionName,
		&i.TaskID,
		&i.Prompt,
		&i.TimeoutNanoseconds,
		&i.ResultKind,
		&i.State,
		&i.Outcome,
		&i.PullRequest,
		&i.WorkflowOutput,
		&i.Failure,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ChangeInput,
		&i.ChangeArtifact,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT session_name, contents, version
FROM publications
WHERE session_name = $1
`

func (q *Queries) GetPublication(ctx context.Context, sessionName string) (Publication, error) {
	row := q.db.QueryRowContext(ctx, getPublication, sessionName)
	var i Publication
	err := row.Scan(&i.SessionName, &i.Contents, &i.Version)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT name, contents, version
FROM workflow_runs
WHERE name = $1
`

func (q *Queries) GetRun(ctx context.Context, name string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, name)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT name, intent_id, runtime_scope, image, definition, repository, initial_ref,
       workflow_run, workflow_step, deletion_storage, created_at
FROM sessions
WHERE name = $1
`

func (q *Queries) GetSession(ctx context.Context, name string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, name)
	var i Session
	err := row.Scan(
		&i.Name,
		&i.IntentID,
		&i.RuntimeScope,
		&i.Image,
		&i.Definition,
		&i.Repository,
		&i.InitialRef,
		&i.WorkflowRun,
		&i.WorkflowStep,
		&i.DeletionStorage,
		&i.CreatedAt,
	)
	return i, err
}

const listDeletingSessions = `-- name: ListDeletingSessions :many
SELECT name, intent_id, runtime_scope, image, definition, repository, initial_ref,
       workflow_run, workflow_step, deletion_storage, created_at
FROM sessions
WHERE deletion_storage IS NOT NULL
ORDER BY name
`

func (q *Queries) ListDeletingSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listDeletingSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Name,
			&i.IntentID,
			&i.RuntimeScope,
			&i.Image,
			&i.Definition,
			&i.Repository,
			&i.InitialRef,
			&i.WorkflowRun,
			&i.WorkflowStep,
			&i.DeletionStorage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT name, contents, version
FROM workflow_runs
ORDER BY name
`

func (q *Queries) ListRuns(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(&i.Name, &i.Contents, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionDeletion = `-- name: SetSessionDeletion :execrows
UPDATE sessions
SET deletion_storage = $2
WHERE name = $1 AND (deletion_storage IS NULL OR deletion_storage = $2)
`

type SetSessionDeletionParams struct {
	Name            string       `json:"name"`
	DeletionStorage sql.NullBool `json:"deletion_storage"`
}

func (q *Queries) SetSessionDeletion(ctx context.Context, arg SetSessionDeletionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionDeletion, arg.Name, arg.DeletionStorage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePublication = `-- name: UpdatePublication :one
UPDATE publications
SET contents = $2, version = version + 1
WHERE session_name = $1 AND version = $3
RETURNING session_name, contents, version
`

type UpdatePublicationParams struct {
	SessionName string `json:"session_name"`
	Contents    []byte `json:"contents"`
	Version     int64  `json:"version"`
}

func (q *Queries) UpdatePublication(ctx context.Context, arg UpdatePublicationParams) (Publication, error) {
	row := q.db.QueryRowContext(ctx, updatePublication, arg.SessionName, arg.Contents, arg.Version)
	var i Publication
	err := row.Scan(&i.SessionName, &i.Contents, &i.Version)
	return i, err
}

const updateRun = `-- name: UpdateRun :one
UPDATE workflow_runs
SET contents = $2, version = version + 1
WHERE name = $1 AND version = $3
RETURNING name, contents, version
`

type UpdateRunParams struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
	Version  int64  `json:"version"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, updateRun, arg.Name, arg.Contents, arg.Version)
	var i WorkflowRun
	err := row.Scan(&i.Name, &i.Contents, &i.Version)
	return i, err
}

const updateSessionTask = `-- name: UpdateSessionTask :execrows
UPDATE session_tasks
SET state = $3,
    outcome = $4,
    pull_request = $5,
    workflow_output = $6,
    change_artifact = $7,
    failure = $8,
    finished_at = $9
WHERE session_name = $1 AND task_id = $2
`

type UpdateSessionTaskParams struct {
	SessionName    string        `json:"session_name"`
	TaskID         string        `json:"task_id"`
	State          string        `json:"state"`
	Outcome        []byte        `json:"outcome"`
	PullRequest    []byte        `json:"pull_request"`
	WorkflowOutput []byte        `json:"workflow_output"`
	ChangeArtifact []byte        `json:"change_artifact"`
	Failure        string        `json:"failure"`
	FinishedAt     sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) UpdateSessionTask(ctx context.Context, arg UpdateSessionTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionTask,
		arg.SessionName,
		arg.TaskID,
		arg.State,
		arg.Outcome,
		arg.PullRequest,
		arg.WorkflowOutput,
		arg.ChangeArtifact,
		arg.Failure,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
